//AUTOGENERATED FILE FROM png2asset
// Conversion args: /players_room.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o /bg_ask.c

#ifndef METASPRITE_bg_ask_H
#define METASPRITE_bg_ask_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_ask_TILE_ORIGIN 104
#define bg_ask_TILE_W 8
#define bg_ask_TILE_H 8
#define bg_ask_WIDTH 128
#define bg_ask_HEIGHT 48
#define bg_ask_TILE_COUNT 94
#define bg_ask_PALETTE_COUNT 1
#define bg_ask_COLORS_PER_PALETTE 4
#define bg_ask_TOTAL_COLORS 4
#define bg_ask_MAP_ATTRIBUTES bg_ask_map_attributes
#define bg_ask_MAP_ATTRIBUTES_WIDTH 16
#define bg_ask_MAP_ATTRIBUTES_HEIGHT 6
#define bg_ask_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_ask_MAP_ATTRIBUTES_PACKED_HEIGHT 6
extern const unsigned char bg_ask_map[96];
extern const unsigned char bg_ask_map_attributes[96];

BANKREF_EXTERN(bg_ask)

extern const palette_color_t bg_ask_palettes[4];
extern const uint8_t bg_ask_tiles[1504];

#endif
