//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o /bg_aachen.c

#ifndef METASPRITE_bg_aachen_H
#define METASPRITE_bg_aachen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_aachen_TILE_ORIGIN 104
#define bg_aachen_TILE_W 8
#define bg_aachen_TILE_H 8
#define bg_aachen_WIDTH 128
#define bg_aachen_HEIGHT 96
#define bg_aachen_TILE_COUNT 78
#define bg_aachen_PALETTE_COUNT 1
#define bg_aachen_COLORS_PER_PALETTE 4
#define bg_aachen_TOTAL_COLORS 4
#define bg_aachen_MAP_ATTRIBUTES bg_aachen_map_attributes
#define bg_aachen_MAP_ATTRIBUTES_WIDTH 16
#define bg_aachen_MAP_ATTRIBUTES_HEIGHT 12
#define bg_aachen_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_aachen_MAP_ATTRIBUTES_PACKED_HEIGHT 12
extern const unsigned char bg_aachen_map[192];
extern const unsigned char bg_aachen_map_attributes[192];

BANKREF_EXTERN(bg_aachen)

extern const palette_color_t bg_aachen_palettes[4];
extern const uint8_t bg_aachen_tiles[1248];

#endif
