//AUTOGENERATED FILE FROM png2asset
// Conversion args: /dark_cave.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o /bg_bwl.c

#ifndef METASPRITE_bg_bwl_H
#define METASPRITE_bg_bwl_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_bwl_TILE_ORIGIN 104
#define bg_bwl_TILE_W 8
#define bg_bwl_TILE_H 8
#define bg_bwl_WIDTH 128
#define bg_bwl_HEIGHT 48
#define bg_bwl_TILE_COUNT 62
#define bg_bwl_PALETTE_COUNT 1
#define bg_bwl_COLORS_PER_PALETTE 4
#define bg_bwl_TOTAL_COLORS 4
#define bg_bwl_MAP_ATTRIBUTES bg_bwl_map_attributes
#define bg_bwl_MAP_ATTRIBUTES_WIDTH 16
#define bg_bwl_MAP_ATTRIBUTES_HEIGHT 6
#define bg_bwl_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_bwl_MAP_ATTRIBUTES_PACKED_HEIGHT 6
extern const unsigned char bg_bwl_map[96];
extern const unsigned char bg_bwl_map_attributes[96];

BANKREF_EXTERN(bg_bwl)

extern const palette_color_t bg_bwl_palettes[4];
extern const uint8_t bg_bwl_tiles[992];

#endif
