//AUTOGENERATED FILE FROM png2asset
// Conversion args: /facility.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o /bg_classroom.c

#ifndef METASPRITE_bg_classroom_H
#define METASPRITE_bg_classroom_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_classroom_TILE_ORIGIN 104
#define bg_classroom_TILE_W 8
#define bg_classroom_TILE_H 8
#define bg_classroom_WIDTH 128
#define bg_classroom_HEIGHT 48
#define bg_classroom_TILE_COUNT 83
#define bg_classroom_PALETTE_COUNT 1
#define bg_classroom_COLORS_PER_PALETTE 4
#define bg_classroom_TOTAL_COLORS 4
#define bg_classroom_MAP_ATTRIBUTES bg_classroom_map_attributes
#define bg_classroom_MAP_ATTRIBUTES_WIDTH 16
#define bg_classroom_MAP_ATTRIBUTES_HEIGHT 6
#define bg_classroom_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_classroom_MAP_ATTRIBUTES_PACKED_HEIGHT 6
extern const unsigned char bg_classroom_map[96];
extern const unsigned char bg_classroom_map_attributes[96];

BANKREF_EXTERN(bg_classroom)

extern const palette_color_t bg_classroom_palettes[4];
extern const uint8_t bg_classroom_tiles[1328];

#endif
