//AUTOGENERATED FILE FROM png2asset
// Conversion args: /cave.png -map -use_map_attributes -bpp 2 -max_palettes 8 -tile_origin 104 -o /bg_cave.c

#ifndef METASPRITE_bg_cave_H
#define METASPRITE_bg_cave_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_cave_TILE_ORIGIN 104
#define bg_cave_TILE_W 8
#define bg_cave_TILE_H 8
#define bg_cave_WIDTH 128
#define bg_cave_HEIGHT 48
#define bg_cave_TILE_COUNT 62
#define bg_cave_PALETTE_COUNT 1
#define bg_cave_COLORS_PER_PALETTE 4
#define bg_cave_TOTAL_COLORS 4
#define bg_cave_MAP_ATTRIBUTES bg_cave_map_attributes
#define bg_cave_MAP_ATTRIBUTES_WIDTH 16
#define bg_cave_MAP_ATTRIBUTES_HEIGHT 6
#define bg_cave_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_cave_MAP_ATTRIBUTES_PACKED_HEIGHT 6
extern const unsigned char bg_cave_map[96];
extern const unsigned char bg_cave_map_attributes[96];

BANKREF_EXTERN(bg_cave)

extern const palette_color_t bg_cave_palettes[4];
extern const uint8_t bg_cave_tiles[992];

#endif
