//AUTOGENERATED FILE FROM png2asset
// Conversion args: /house.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o /bg_living_room.c

#ifndef METASPRITE_bg_living_room_H
#define METASPRITE_bg_living_room_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_living_room_TILE_ORIGIN 104
#define bg_living_room_TILE_W 8
#define bg_living_room_TILE_H 8
#define bg_living_room_WIDTH 128
#define bg_living_room_HEIGHT 96
#define bg_living_room_TILE_COUNT 93
#define bg_living_room_PALETTE_COUNT 1
#define bg_living_room_COLORS_PER_PALETTE 4
#define bg_living_room_TOTAL_COLORS 4
#define bg_living_room_MAP_ATTRIBUTES bg_living_room_map_attributes
#define bg_living_room_MAP_ATTRIBUTES_WIDTH 16
#define bg_living_room_MAP_ATTRIBUTES_HEIGHT 12
#define bg_living_room_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_living_room_MAP_ATTRIBUTES_PACKED_HEIGHT 12
extern const unsigned char bg_living_room_map[192];
extern const unsigned char bg_living_room_map_attributes[192];

BANKREF_EXTERN(bg_living_room)

extern const palette_color_t bg_living_room_palettes[4];
extern const uint8_t bg_living_room_tiles[1488];

#endif
