//AUTOGENERATED FILE FROM png2asset
// Conversion args: /game_corner.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o /bg_spain.c

#ifndef METASPRITE_bg_spain_H
#define METASPRITE_bg_spain_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_spain_TILE_ORIGIN 104
#define bg_spain_TILE_W 8
#define bg_spain_TILE_H 8
#define bg_spain_WIDTH 128
#define bg_spain_HEIGHT 96
#define bg_spain_TILE_COUNT 121
#define bg_spain_PALETTE_COUNT 1
#define bg_spain_COLORS_PER_PALETTE 4
#define bg_spain_TOTAL_COLORS 4
#define bg_spain_MAP_ATTRIBUTES bg_spain_map_attributes
#define bg_spain_MAP_ATTRIBUTES_WIDTH 16
#define bg_spain_MAP_ATTRIBUTES_HEIGHT 12
#define bg_spain_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_spain_MAP_ATTRIBUTES_PACKED_HEIGHT 12
extern const unsigned char bg_spain_map[192];
extern const unsigned char bg_spain_map_attributes[192];

BANKREF_EXTERN(bg_spain)

extern const palette_color_t bg_spain_palettes[4];
extern const uint8_t bg_spain_tiles[1936];

#endif
