//AUTOGENERATED FILE FROM png2asset
// Conversion args: /park.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o /bg_schoolyard.c

#ifndef METASPRITE_bg_schoolyard_H
#define METASPRITE_bg_schoolyard_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_schoolyard_TILE_ORIGIN 104
#define bg_schoolyard_TILE_W 8
#define bg_schoolyard_TILE_H 8
#define bg_schoolyard_WIDTH 128
#define bg_schoolyard_HEIGHT 96
#define bg_schoolyard_TILE_COUNT 94
#define bg_schoolyard_PALETTE_COUNT 1
#define bg_schoolyard_COLORS_PER_PALETTE 4
#define bg_schoolyard_TOTAL_COLORS 4
#define bg_schoolyard_MAP_ATTRIBUTES bg_schoolyard_map_attributes
#define bg_schoolyard_MAP_ATTRIBUTES_WIDTH 16
#define bg_schoolyard_MAP_ATTRIBUTES_HEIGHT 12
#define bg_schoolyard_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_schoolyard_MAP_ATTRIBUTES_PACKED_HEIGHT 12
extern const unsigned char bg_schoolyard_map[192];
extern const unsigned char bg_schoolyard_map_attributes[192];

BANKREF_EXTERN(bg_schoolyard)

extern const palette_color_t bg_schoolyard_palettes[4];
extern const uint8_t bg_schoolyard_tiles[1504];

#endif
