//AUTOGENERATED FILE FROM png2asset
// Conversion args: \schoolyard.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o \scene_schoolyard.c

#ifndef METASPRITE_scene_schoolyard_H
#define METASPRITE_scene_schoolyard_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene_schoolyard_TILE_ORIGIN 104
#define scene_schoolyard_TILE_W 8
#define scene_schoolyard_TILE_H 8
#define scene_schoolyard_WIDTH 160
#define scene_schoolyard_HEIGHT 144
#define scene_schoolyard_TILE_COUNT 58
#define scene_schoolyard_PALETTE_COUNT 1
#define scene_schoolyard_COLORS_PER_PALETTE 4
#define scene_schoolyard_TOTAL_COLORS 4
#define scene_schoolyard_MAP_ATTRIBUTES scene_schoolyard_map_attributes
#define scene_schoolyard_MAP_ATTRIBUTES_WIDTH 20
#define scene_schoolyard_MAP_ATTRIBUTES_HEIGHT 18
#define scene_schoolyard_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define scene_schoolyard_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char scene_schoolyard_map[360];
extern const unsigned char scene_schoolyard_map_attributes[360];

BANKREF_EXTERN(scene_schoolyard)

extern const palette_color_t scene_schoolyard_palettes[4];
extern const uint8_t scene_schoolyard_tiles[928];

#endif
