//AUTOGENERATED FILE FROM png2asset
// Conversion args: \spain_bedroom.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o \scene_spain_bedroom.c

#ifndef METASPRITE_scene_spain_bedroom_H
#define METASPRITE_scene_spain_bedroom_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene_spain_bedroom_TILE_ORIGIN 104
#define scene_spain_bedroom_TILE_W 8
#define scene_spain_bedroom_TILE_H 8
#define scene_spain_bedroom_WIDTH 160
#define scene_spain_bedroom_HEIGHT 144
#define scene_spain_bedroom_TILE_COUNT 62
#define scene_spain_bedroom_PALETTE_COUNT 1
#define scene_spain_bedroom_COLORS_PER_PALETTE 4
#define scene_spain_bedroom_TOTAL_COLORS 4
#define scene_spain_bedroom_MAP_ATTRIBUTES scene_spain_bedroom_map_attributes
#define scene_spain_bedroom_MAP_ATTRIBUTES_WIDTH 20
#define scene_spain_bedroom_MAP_ATTRIBUTES_HEIGHT 18
#define scene_spain_bedroom_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define scene_spain_bedroom_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char scene_spain_bedroom_map[360];
extern const unsigned char scene_spain_bedroom_map_attributes[360];

BANKREF_EXTERN(scene_spain_bedroom)

extern const palette_color_t scene_spain_bedroom_palettes[4];
extern const uint8_t scene_spain_bedroom_tiles[992];

#endif
