//AUTOGENERATED FILE FROM png2asset
// Conversion args: \bwl.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o \scene_bwl.c

#ifndef METASPRITE_scene_bwl_H
#define METASPRITE_scene_bwl_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene_bwl_TILE_ORIGIN 104
#define scene_bwl_TILE_W 8
#define scene_bwl_TILE_H 8
#define scene_bwl_WIDTH 160
#define scene_bwl_HEIGHT 144
#define scene_bwl_TILE_COUNT 46
#define scene_bwl_PALETTE_COUNT 1
#define scene_bwl_COLORS_PER_PALETTE 4
#define scene_bwl_TOTAL_COLORS 4
#define scene_bwl_MAP_ATTRIBUTES scene_bwl_map_attributes
#define scene_bwl_MAP_ATTRIBUTES_WIDTH 20
#define scene_bwl_MAP_ATTRIBUTES_HEIGHT 18
#define scene_bwl_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define scene_bwl_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char scene_bwl_map[360];
extern const unsigned char scene_bwl_map_attributes[360];

BANKREF_EXTERN(scene_bwl)

extern const palette_color_t scene_bwl_palettes[4];
extern const uint8_t scene_bwl_tiles[736];

#endif
