//AUTOGENERATED FILE FROM png2asset
// Conversion args: \title.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 0 -o \scene_title.c

#ifndef METASPRITE_scene_title_H
#define METASPRITE_scene_title_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene_title_TILE_ORIGIN 0
#define scene_title_TILE_W 8
#define scene_title_TILE_H 8
#define scene_title_WIDTH 160
#define scene_title_HEIGHT 144
#define scene_title_TILE_COUNT 162
#define scene_title_PALETTE_COUNT 1
#define scene_title_COLORS_PER_PALETTE 4
#define scene_title_TOTAL_COLORS 4
#define scene_title_MAP_ATTRIBUTES scene_title_map_attributes
#define scene_title_MAP_ATTRIBUTES_WIDTH 20
#define scene_title_MAP_ATTRIBUTES_HEIGHT 18
#define scene_title_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define scene_title_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char scene_title_map[360];
extern const unsigned char scene_title_map_attributes[360];

BANKREF_EXTERN(scene_title)

extern const palette_color_t scene_title_palettes[4];
extern const uint8_t scene_title_tiles[2592];

#endif
