//AUTOGENERATED FILE FROM png2asset
// Conversion args: \aachen.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o \scene_aachen.c

#ifndef METASPRITE_scene_aachen_H
#define METASPRITE_scene_aachen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene_aachen_TILE_ORIGIN 104
#define scene_aachen_TILE_W 8
#define scene_aachen_TILE_H 8
#define scene_aachen_WIDTH 160
#define scene_aachen_HEIGHT 144
#define scene_aachen_TILE_COUNT 100
#define scene_aachen_PALETTE_COUNT 1
#define scene_aachen_COLORS_PER_PALETTE 4
#define scene_aachen_TOTAL_COLORS 4
#define scene_aachen_MAP_ATTRIBUTES scene_aachen_map_attributes
#define scene_aachen_MAP_ATTRIBUTES_WIDTH 20
#define scene_aachen_MAP_ATTRIBUTES_HEIGHT 18
#define scene_aachen_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define scene_aachen_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char scene_aachen_map[360];
extern const unsigned char scene_aachen_map_attributes[360];

BANKREF_EXTERN(scene_aachen)

extern const palette_color_t scene_aachen_palettes[4];
extern const uint8_t scene_aachen_tiles[1600];

#endif
