//AUTOGENERATED FILE FROM png2asset
// Conversion args: \classroom.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o \scene_classroom.c

#ifndef METASPRITE_scene_classroom_H
#define METASPRITE_scene_classroom_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene_classroom_TILE_ORIGIN 104
#define scene_classroom_TILE_W 8
#define scene_classroom_TILE_H 8
#define scene_classroom_WIDTH 160
#define scene_classroom_HEIGHT 144
#define scene_classroom_TILE_COUNT 83
#define scene_classroom_PALETTE_COUNT 1
#define scene_classroom_COLORS_PER_PALETTE 4
#define scene_classroom_TOTAL_COLORS 4
#define scene_classroom_MAP_ATTRIBUTES scene_classroom_map_attributes
#define scene_classroom_MAP_ATTRIBUTES_WIDTH 20
#define scene_classroom_MAP_ATTRIBUTES_HEIGHT 18
#define scene_classroom_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define scene_classroom_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char scene_classroom_map[360];
extern const unsigned char scene_classroom_map_attributes[360];

BANKREF_EXTERN(scene_classroom)

extern const palette_color_t scene_classroom_palettes[4];
extern const uint8_t scene_classroom_tiles[1328];

#endif
