//AUTOGENERATED FILE FROM png2asset
// Conversion args: \living_room.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o \scene_living_room.c

#ifndef METASPRITE_scene_living_room_H
#define METASPRITE_scene_living_room_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene_living_room_TILE_ORIGIN 104
#define scene_living_room_TILE_W 8
#define scene_living_room_TILE_H 8
#define scene_living_room_WIDTH 160
#define scene_living_room_HEIGHT 144
#define scene_living_room_TILE_COUNT 92
#define scene_living_room_PALETTE_COUNT 1
#define scene_living_room_COLORS_PER_PALETTE 4
#define scene_living_room_TOTAL_COLORS 4
#define scene_living_room_MAP_ATTRIBUTES scene_living_room_map_attributes
#define scene_living_room_MAP_ATTRIBUTES_WIDTH 20
#define scene_living_room_MAP_ATTRIBUTES_HEIGHT 18
#define scene_living_room_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define scene_living_room_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char scene_living_room_map[360];
extern const unsigned char scene_living_room_map_attributes[360];

BANKREF_EXTERN(scene_living_room)

extern const palette_color_t scene_living_room_palettes[4];
extern const uint8_t scene_living_room_tiles[1472];

#endif
