//AUTOGENERATED FILE FROM png2asset
// Conversion args: \spain_bar.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o \scene_spain_bar.c

#ifndef METASPRITE_scene_spain_bar_H
#define METASPRITE_scene_spain_bar_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene_spain_bar_TILE_ORIGIN 104
#define scene_spain_bar_TILE_W 8
#define scene_spain_bar_TILE_H 8
#define scene_spain_bar_WIDTH 160
#define scene_spain_bar_HEIGHT 144
#define scene_spain_bar_TILE_COUNT 78
#define scene_spain_bar_PALETTE_COUNT 1
#define scene_spain_bar_COLORS_PER_PALETTE 4
#define scene_spain_bar_TOTAL_COLORS 4
#define scene_spain_bar_MAP_ATTRIBUTES scene_spain_bar_map_attributes
#define scene_spain_bar_MAP_ATTRIBUTES_WIDTH 20
#define scene_spain_bar_MAP_ATTRIBUTES_HEIGHT 18
#define scene_spain_bar_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define scene_spain_bar_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char scene_spain_bar_map[360];
extern const unsigned char scene_spain_bar_map_attributes[360];

BANKREF_EXTERN(scene_spain_bar)

extern const palette_color_t scene_spain_bar_palettes[4];
extern const uint8_t scene_spain_bar_tiles[1248];

#endif
