//AUTOGENERATED FILE FROM png2asset
// Conversion args: \ask.png -map -use_map_attributes -bpp 2 -max_palettes 1 -tile_origin 104 -o \scene_ask.c

#ifndef METASPRITE_scene_ask_H
#define METASPRITE_scene_ask_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define scene_ask_TILE_ORIGIN 104
#define scene_ask_TILE_W 8
#define scene_ask_TILE_H 8
#define scene_ask_WIDTH 160
#define scene_ask_HEIGHT 144
#define scene_ask_TILE_COUNT 61
#define scene_ask_PALETTE_COUNT 1
#define scene_ask_COLORS_PER_PALETTE 4
#define scene_ask_TOTAL_COLORS 4
#define scene_ask_MAP_ATTRIBUTES scene_ask_map_attributes
#define scene_ask_MAP_ATTRIBUTES_WIDTH 20
#define scene_ask_MAP_ATTRIBUTES_HEIGHT 18
#define scene_ask_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define scene_ask_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char scene_ask_map[360];
extern const unsigned char scene_ask_map_attributes[360];

BANKREF_EXTERN(scene_ask)

extern const palette_color_t scene_ask_palettes[4];
extern const uint8_t scene_ask_tiles[976];

#endif
