//AUTOGENERATED FILE FROM png2asset
// Conversion args: \portrait_bramt.png -map -bpp 2 -max_palettes 1 -tile_origin 0 -o \portrait_bramt.c

#ifndef METASPRITE_portrait_bramt_H
#define METASPRITE_portrait_bramt_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define portrait_bramt_TILE_ORIGIN 0
#define portrait_bramt_TILE_W 8
#define portrait_bramt_TILE_H 8
#define portrait_bramt_WIDTH 40
#define portrait_bramt_HEIGHT 40
#define portrait_bramt_TILE_COUNT 20
#define portrait_bramt_PALETTE_COUNT 1
#define portrait_bramt_COLORS_PER_PALETTE 4
#define portrait_bramt_TOTAL_COLORS 4
#define portrait_bramt_MAP_ATTRIBUTES 0
extern const unsigned char portrait_bramt_map[25];
#define portrait_bramt_map_attributes portrait_bramt_map

BANKREF_EXTERN(portrait_bramt)

extern const palette_color_t portrait_bramt_palettes[4];
extern const uint8_t portrait_bramt_tiles[320];

#endif
