//AUTOGENERATED FILE FROM png2asset
// Conversion args: \portrait_teacher.png -map -bpp 2 -max_palettes 1 -tile_origin 0 -o \portrait_teacher.c

#ifndef METASPRITE_portrait_teacher_H
#define METASPRITE_portrait_teacher_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define portrait_teacher_TILE_ORIGIN 0
#define portrait_teacher_TILE_W 8
#define portrait_teacher_TILE_H 8
#define portrait_teacher_WIDTH 40
#define portrait_teacher_HEIGHT 40
#define portrait_teacher_TILE_COUNT 18
#define portrait_teacher_PALETTE_COUNT 1
#define portrait_teacher_COLORS_PER_PALETTE 4
#define portrait_teacher_TOTAL_COLORS 4
#define portrait_teacher_MAP_ATTRIBUTES 0
extern const unsigned char portrait_teacher_map[25];
#define portrait_teacher_map_attributes portrait_teacher_map

BANKREF_EXTERN(portrait_teacher)

extern const palette_color_t portrait_teacher_palettes[4];
extern const uint8_t portrait_teacher_tiles[288];

#endif
