//AUTOGENERATED FILE FROM png2asset
// Conversion args: \portrait_friets.png -map -bpp 2 -max_palettes 1 -tile_origin 0 -o \portrait_friets.c

#ifndef METASPRITE_portrait_friets_H
#define METASPRITE_portrait_friets_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define portrait_friets_TILE_ORIGIN 0
#define portrait_friets_TILE_W 8
#define portrait_friets_TILE_H 8
#define portrait_friets_WIDTH 40
#define portrait_friets_HEIGHT 40
#define portrait_friets_TILE_COUNT 14
#define portrait_friets_PALETTE_COUNT 1
#define portrait_friets_COLORS_PER_PALETTE 4
#define portrait_friets_TOTAL_COLORS 4
#define portrait_friets_MAP_ATTRIBUTES 0
extern const unsigned char portrait_friets_map[25];
#define portrait_friets_map_attributes portrait_friets_map

BANKREF_EXTERN(portrait_friets)

extern const palette_color_t portrait_friets_palettes[4];
extern const uint8_t portrait_friets_tiles[224];

#endif
