//AUTOGENERATED FILE FROM png2asset
// Conversion args: \portrait_dad.png -map -bpp 2 -max_palettes 1 -tile_origin 0 -o \portrait_dad.c

#ifndef METASPRITE_portrait_dad_H
#define METASPRITE_portrait_dad_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define portrait_dad_TILE_ORIGIN 0
#define portrait_dad_TILE_W 8
#define portrait_dad_TILE_H 8
#define portrait_dad_WIDTH 40
#define portrait_dad_HEIGHT 40
#define portrait_dad_TILE_COUNT 14
#define portrait_dad_PALETTE_COUNT 1
#define portrait_dad_COLORS_PER_PALETTE 4
#define portrait_dad_TOTAL_COLORS 4
#define portrait_dad_MAP_ATTRIBUTES 0
extern const unsigned char portrait_dad_map[25];
#define portrait_dad_map_attributes portrait_dad_map

BANKREF_EXTERN(portrait_dad)

extern const palette_color_t portrait_dad_palettes[4];
extern const uint8_t portrait_dad_tiles[224];

#endif
