//AUTOGENERATED FILE FROM png2asset
// Conversion args: \portrait_tobi.png -map -bpp 2 -max_palettes 1 -tile_origin 0 -o \portrait_tobi.c

#ifndef METASPRITE_portrait_tobi_H
#define METASPRITE_portrait_tobi_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define portrait_tobi_TILE_ORIGIN 0
#define portrait_tobi_TILE_W 8
#define portrait_tobi_TILE_H 8
#define portrait_tobi_WIDTH 40
#define portrait_tobi_HEIGHT 40
#define portrait_tobi_TILE_COUNT 15
#define portrait_tobi_PALETTE_COUNT 1
#define portrait_tobi_COLORS_PER_PALETTE 4
#define portrait_tobi_TOTAL_COLORS 4
#define portrait_tobi_MAP_ATTRIBUTES 0
extern const unsigned char portrait_tobi_map[25];
#define portrait_tobi_map_attributes portrait_tobi_map

BANKREF_EXTERN(portrait_tobi)

extern const palette_color_t portrait_tobi_palettes[4];
extern const uint8_t portrait_tobi_tiles[240];

#endif
