//AUTOGENERATED FILE FROM png2asset
// Conversion args: \portrait_aronian.png -map -bpp 2 -max_palettes 1 -tile_origin 0 -o \portrait_aronian.c

#ifndef METASPRITE_portrait_aronian_H
#define METASPRITE_portrait_aronian_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define portrait_aronian_TILE_ORIGIN 0
#define portrait_aronian_TILE_W 8
#define portrait_aronian_TILE_H 8
#define portrait_aronian_WIDTH 40
#define portrait_aronian_HEIGHT 40
#define portrait_aronian_TILE_COUNT 19
#define portrait_aronian_PALETTE_COUNT 1
#define portrait_aronian_COLORS_PER_PALETTE 4
#define portrait_aronian_TOTAL_COLORS 4
#define portrait_aronian_MAP_ATTRIBUTES 0
extern const unsigned char portrait_aronian_map[25];
#define portrait_aronian_map_attributes portrait_aronian_map

BANKREF_EXTERN(portrait_aronian)

extern const palette_color_t portrait_aronian_palettes[4];
extern const uint8_t portrait_aronian_tiles[304];

#endif
