//AUTOGENERATED FILE FROM png2asset
// Conversion args: \portrait_waitress.png -map -bpp 2 -max_palettes 1 -tile_origin 0 -o \portrait_waitress.c

#ifndef METASPRITE_portrait_waitress_H
#define METASPRITE_portrait_waitress_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define portrait_waitress_TILE_ORIGIN 0
#define portrait_waitress_TILE_W 8
#define portrait_waitress_TILE_H 8
#define portrait_waitress_WIDTH 40
#define portrait_waitress_HEIGHT 40
#define portrait_waitress_TILE_COUNT 19
#define portrait_waitress_PALETTE_COUNT 1
#define portrait_waitress_COLORS_PER_PALETTE 4
#define portrait_waitress_TOTAL_COLORS 4
#define portrait_waitress_MAP_ATTRIBUTES 0
extern const unsigned char portrait_waitress_map[25];
#define portrait_waitress_map_attributes portrait_waitress_map

BANKREF_EXTERN(portrait_waitress)

extern const palette_color_t portrait_waitress_palettes[4];
extern const uint8_t portrait_waitress_tiles[304];

#endif
