//AUTOGENERATED FILE FROM png2asset
// Conversion args: \portrait_michel.png -map -bpp 2 -max_palettes 1 -tile_origin 0 -o \portrait_michel.c

#ifndef METASPRITE_portrait_michel_H
#define METASPRITE_portrait_michel_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define portrait_michel_TILE_ORIGIN 0
#define portrait_michel_TILE_W 8
#define portrait_michel_TILE_H 8
#define portrait_michel_WIDTH 40
#define portrait_michel_HEIGHT 40
#define portrait_michel_TILE_COUNT 17
#define portrait_michel_PALETTE_COUNT 1
#define portrait_michel_COLORS_PER_PALETTE 4
#define portrait_michel_TOTAL_COLORS 4
#define portrait_michel_MAP_ATTRIBUTES 0
extern const unsigned char portrait_michel_map[25];
#define portrait_michel_map_attributes portrait_michel_map

BANKREF_EXTERN(portrait_michel)

extern const palette_color_t portrait_michel_palettes[4];
extern const uint8_t portrait_michel_tiles[272];

#endif
