//AUTOGENERATED FILE FROM png2asset
// Conversion args: \portrait_npc.png -map -bpp 2 -max_palettes 1 -tile_origin 0 -o \portrait_npc.c

#ifndef METASPRITE_portrait_npc_H
#define METASPRITE_portrait_npc_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define portrait_npc_TILE_ORIGIN 0
#define portrait_npc_TILE_W 8
#define portrait_npc_TILE_H 8
#define portrait_npc_WIDTH 40
#define portrait_npc_HEIGHT 40
#define portrait_npc_TILE_COUNT 23
#define portrait_npc_PALETTE_COUNT 1
#define portrait_npc_COLORS_PER_PALETTE 4
#define portrait_npc_TOTAL_COLORS 4
#define portrait_npc_MAP_ATTRIBUTES 0
extern const unsigned char portrait_npc_map[25];
#define portrait_npc_map_attributes portrait_npc_map

BANKREF_EXTERN(portrait_npc)

extern const palette_color_t portrait_npc_palettes[4];
extern const uint8_t portrait_npc_tiles[368];

#endif
